server:
  port: 8002
spring:
  data:
    mongodb:
      database: dbBank
      host: 127.0.0.1
      port: 27017
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
resilience4j:
    circuitbreaker:
        instances:
            passiveCB:
                slidingWindowSize: 3
                slidingWindowType: COUNT_BASED
                #waitDurationInOpenState: 5
                waitInterval: 100
                failureRateThreshold: 50
                permittedNumberOfCallsInHalfOpenState: 5
                registerHealthIndicator: true
                #register-health-indicator: true
                allowHealthIndicatorToFail: true
        configs:
            default:
                registerHealthIndicator: true

management.health.circuitbreakers.enabled: true
management:
  endpoint:
    health:
        show-details: always